name: DavidDavis3078796430

on:
  workflow_dispatch:

jobs:
  run-files:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job-name: [job1,job2,job3,job4,job5,job6,job7,job8,job9,job10,job11,job12,job13,job14,job15,job16,job17,job18,job19,job20,job21,job22,job23,job24,job25,job26,job27,job28,job29,job30,job31,job32,job33,job34,job35]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Java Files
        shell: pwsh
        run: |
          Start-Process java -ArgumentList "-jar", "MatthewScott4362588642.jar"
          java -jar AnthonyKing2740215910.jar
